server:
  port: 9000

# feign配置
feign:
  httpclient:
    enabled: false
  okhttp:
    enabled: true
# ribbon 配置
ribbon:
  OkToRetryOnAllOperations: false # 对所有操作请求都进行重试,默认false
  ReadTimeout: 10000   # 负载均衡超时时间，默认值5000
  ConnectTimeout: 10000 # ribbon请求连接的超时时间，默认值2000
  MaxAutoRetries: 0     # 对当前实例的重试次数，默认0
  MaxAutoRetriesNextServer: 1 # 对切换实例的重试次数，默认1

#开启SpringBoot Admin的监控
management:
  endpoints:
    web:
      exposure:
        include: "*"
